[project]
name = "oci_bucket"
version = "0.1.0"
description = "Package for easy Oci Buckets management in python."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "oci>=2.145.0"
]
